baseurl = "https://ocrug.org/"
title = "Orange County R User Group"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# Define the number of posts per page
paginate = 10


buildfuture = true

[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 2

[[menu.main]]
    name = "Code of Conduct"
    identifier = "COC"
    url  = "https://github.com/ocrug/hackathon-2019/blob/master/code-of-conduct.md"
    weight = 4

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 3

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    # url = "https://github.com/devcows/hugo-universal-theme"
    url = "https://github.com/ocrug"
    pre = "<i class='fa fa-2x fa-github'></i>"

# [[menu.topbar]]
#     weight = 2
#     name = "Facebook"
#     url = "http://facebook.com"
#     pre = "<i class='fa fa-2x fa-facebook'></i>"

[[menu.topbar]]
    weight = 3
    name = "Slack"
    url = "https://ocrug.slack.com/"
    # pre = "<i class='fa fa-2x fa-twitter'></i>"
    pre = "<i class='fa fa-2x fa-slack'></i>"


[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:orangecounty.rug@gmail.com"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "DevCows"
    defaultKeywords = ["devows", "hugo", "go"]
    defaultDescription = "Site template made by devcows using hugo"

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "violet"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "bronze10000@gmail.com"

    # about_us = "<p></p>"
    # copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    # logo = "img/logo.png"
    logo = "img/OCRUG_logo_small3.png"
    logo_small = "img/OCRUG_logo_small3.png"
    address = """<p><strong>PeopleSpace</strong>
        <br>1691 Kettering Street
        <br>Irvine, CA
        <br>
        <strong>USA</strong>
      </p>
      """
    latitude = "33.698155"
    longitude = "-117.846824"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = false
    icon = "fa fa-file-code-o"
    title = "Do you want to see more?"
    subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
    link_url = "#"
    link_text = "Check other homepages"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "From our blog"
    subtitle = "You can browse our list of posts that describe previous and future presentations."
# ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]